language: c

env:
    global:
        - secure: "HUPlNlwRV9ZvcZA6xIpewe6on9lgSctXjI2EnOwtuRn20DKScIsPYtz+RBX7+uKVVyQLXfT+s2Q/bmvq2eG0MHujbsGZV+mn7bx+24/Lu4gtNqpy0+eSpA3ivRCRswj7FYYSKuudpz11KvEL8BPxO3Ipthz/cy/d+dUFdhZ4MQE="
    matrix:
        - hyperopt=0.0.2   python=2.6
        - hyperopt=dev     python=2.7
        - hyperopt=0.0.2   python=2.7
        - hyperopt=none    python=3.4

install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh
  - bash Miniconda-latest-Linux-x86_64.sh -b
  - export PATH=$HOME/miniconda/bin:$PATH

  # install requirements file in python
  - conda create --yes -n test python=$python `cat requirements.txt | xargs`
  - source activate test

  # instal python2.6 backports
  - '[ "$python" = "2.6" ]
      && conda install --yes pip
      && pip install importlib argparse
      || echo ""'

  # install extra dependency for style checking
  - conda install --yes flake8

  # instal hyperopt dependencies
  - '[ "$hyperopt" != "none" ]
      && conda install --yes pymongo networkx
      || echo ""'

  # install hyperopt
  - '[ "$hyperopt" = "0.0.2" ]
      && conda install --yes pip
      && pip install hyperopt
      || echo ""'
  - '[ "$hyperopt" = "dev" ]
      && git clone https://github.com/hyperopt/hyperopt.git
      && cd hyperopt
      && python setup.py -q install
      && cd -
      && rm -rf hyperopt
      || echo ""'

  - python setup.py install


script:
  - nosetests -v
  # exclude versioneer.py and _version.py from style checking, since we don't
  # write/maintain them
  - flake8 `find . -name '*.py'  ! -name build ! -path './build/*' !
            -path './docs*' ! -name versioneer.py ! -name _version.py | xargs`
